quarkus.application.name=nhatro-mvp
quarkus.http.port=8080

quarkus.datasource.db-kind=mysql
quarkus.datasource.username=${DB_USERNAME:root}
quarkus.datasource.password=${DB_PASSWORD:khanh151005}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:mysql://127.0.0.1:3306/nhatro_mvp?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Ho_Chi_Minh}

quarkus.hibernate-orm.schema-management.strategy=validate
quarkus.hibernate-orm.log.sql=false
quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=db/migration

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=/.*/
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Authorization,Content-Type

app.jwt.issuer=nhatro-mvp
app.jwt.secret=${JWT_SECRET:change-this-secret-in-production-at-least-32-characters}
app.jwt.expiration-seconds=86400
